[build]
  publish = "."
  command = "# No build command needed for plain HTML/CSS/JS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "22.14.0"